### PR TITLE
PPP and Documentation Fixes

### LINKED ISSUE #207: [PE-D][Tester F] Searching for an item by EXPIRY_DATE_RANGE does not work as intended.
The format given uses `-e 11.11.2023..`, which fails. The search only works if `-e 11-11-2023..` is used.

Here is what I tested:

-------------
Labels: `severity.High` `type.DocumentationBug`
original: wallywallywally/ped#4

### PR DESCRIPTION
**Pull request by nkotaa**
Aside from adding my PPP, this closes #207

### CODE REVIEW

File: src/main/java/seedu/binbash/parser/Parser.java [hunk 1]
```diff
@@ -167,6 +167,9 @@ static int parseIntOptionValue(String argument, String option) throws ParseExcep
         if (longValue > Integer.MAX_VALUE) {
             throw new ParseException(option + " too large!");
         }
+        if (longValue < Integer.MIN_VALUE) {
+            throw new ParseException(option + " too small!");
+        }
```
Comment (YHWong20) [inline src/main/java/seedu/binbash/parser/Parser.java:172]: Good catch!

**Review by YHWong20 — APPROVED** [review]
Thank you for your contributions to the tP!! :)
